### ISSUE TITLE
"ProxyJump" statement doesn't work

### ISSUE THREAD

**Issue by Hubro** [ObserverOfTime/tree-sitter-ssh-config#8]
![image](https://github.com/ObserverOfTime/tree-sitter-ssh-config/assets/597206/c068e020-9632-452c-9edd-abcdfcbc8082)

**Comment by ObserverOfTime** [comment]
Thanks for finding these.

**Comment by Hubro** [comment]
My pleasure, my SSH config looks a lot better now :grin:
